### ISSUE TITLE
Different error numbers

### ISSUE THREAD

**Issue by ChristianSaile** [bee-eater/SystemDumpViewer#11]
Hi,

I am looking into a customer problem on an axis.
He send me a screenshot from the System Diagnose Manager and then the SystemDump.

The error numbers differ from each other.
The number in the SystemDump is no known error number of B&R.

![Screenshot_SysDump_FloatingPointError_SysDumpV2_3_0_27014](https://user-images.githubusercontent.com/95356645/144240024-1feaf31d-51d5-4a27-b832-22c999df9b58.png)
![SDM Hubachse Meldung](https://user-images.githubusercontent.com/95356645/144240050-6155bd70-9e15-4b56-8f9f-17e2b6caaf4b.PNG)

Greetings
Christian

**Comment by bee-eater** [comment]
Hello Christian,

please always attach a Systemdump to reproduce the issue, so it can be analyzed. Thanks!

Best regards,
Marcel

**Comment by ChristianSaile** [comment]
Hello Marcel,

sorry, here is the the SystemDump.


Thanks for the quick reply.
Christian

Von: Marcel Krausert ***@***.***>
Gesendet: Mittwoch, 1. Dezember 2021 15:05
An: bee-eater/SystemDumpViewer ***@***.***>
Cc: Christian Saile ***@***.***>; Author ***@***.***>
Betreff: Re: [bee-eater/SystemDumpViewer] Different error numbers (Issue #11)

This email originated from outside of your organization. Please do not click on links or open attachments unless you recognize the sender and know the content is safe.


Hello Christian,

please always attach a Systemdump to reproduce the issue, so it can be analyzed. Thanks!

Best regards,
Marcel

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbee-eater%2FSystemDumpViewer%2Fissues%2F11%23issuecomment-983672446&data=04%7C01%7Cchristian.saile%40br-automation.com%7C7b45dba7bbf14875acfb08d9b4d393b8%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739643090380740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rkK%2FU5G3FK%2FZDyywOvdNSJeHiwh3PRN7A1wo%2BOPsoYM%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWXQNZL72IOOQBLKBXHZTWDUOYTRBANCNFSM5JEN5M5A&data=04%7C01%7Cchristian.saile%40br-automation.com%7C7b45dba7bbf14875acfb08d9b4d393b8%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739643090380740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=48g1k95TBqxkai9mV01jJonH8%2F6wiKKkPuvQHm%2BNRXQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristian.saile%40br-automation.com%7C7b45dba7bbf14875acfb08d9b4d393b8%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739643090390738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6%2FqjHRll0%2BEO99lDIcLI%2F%2F15broNBmXvzBrZ%2B2Oj1ek%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchristian.saile%40br-automation.com%7C7b45dba7bbf14875acfb08d9b4d393b8%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739643090390738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o9XOJR1fzpkCcF13H5PUVeMrel4K3t%2BVWB9xc7X%2FWoM%3D&reserved=0>.

**Comment by bee-eater** [comment]
[Systemdump.txt](https://github.com/bee-eater/SystemDumpViewer/files/7634673/Systemdump.txt)

**Comment by ChristianSaile** [comment]
Hello Marcel,

what do I do with this .txt?

Greetings
Christian


Von: Marcel Krausert ***@***.***>
Gesendet: Mittwoch, 1. Dezember 2021 15:36
An: bee-eater/SystemDumpViewer ***@***.***>
Cc: Christian Saile ***@***.***>; Author ***@***.***>
Betreff: Re: [bee-eater/SystemDumpViewer] Different error numbers (Issue #11)

This email originated from outside of your organization. Please do not click on links or open attachments unless you recognize the sender and know the content is safe.


Systemdump.txt<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbee-eater%2FSystemDumpViewer%2Ffiles%2F7634673%2FSystemdump.txt&data=04%7C01%7Cchristian.saile%40br-automation.com%7Ce1b7f8a1234c4f85358408d9b4d7d996%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739661429748293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4Rzashq0O1UJ6cFPPeNidqJxE%2FlK9z7%2BPpVl%2F026IVM%3D&reserved=0>

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbee-eater%2FSystemDumpViewer%2Fissues%2F11%23issuecomment-983702320&data=04%7C01%7Cchristian.saile%40br-automation.com%7Ce1b7f8a1234c4f85358408d9b4d7d996%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739661429758288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x0FZCpndL2yt6E173%2Fr7RtPZ%2BUgzB93LpvR3gGyS7sw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWXQNZKFIPOKTDEVKX5FTCDUOYXDXANCNFSM5JEN5M5A&data=04%7C01%7Cchristian.saile%40br-automation.com%7Ce1b7f8a1234c4f85358408d9b4d7d996%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739661429758288%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=37y88gmM4G9b5Ue9xMT%2Fo9PgfrY4syAfY7APmsbnk9Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchristian.saile%40br-automation.com%7Ce1b7f8a1234c4f85358408d9b4d7d996%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739661429768282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fUi4wcLMztof2Edj7NMGyUPsK%2FyY%2F1KN9bk1VJi%2B%2F8E%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchristian.saile%40br-automation.com%7Ce1b7f8a1234c4f85358408d9b4d7d996%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C637739661429768282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DB9FmdRdeLcTnnY6718BEfUsd8oACwXvI9vL2CdUpXE%3D&reserved=0>.

**Comment by bee-eater** [comment]
Nothing, that is the Systemdump.xml to reproduce the issue. Since it wasn't attached in your post, I attached it. The ending .xml is not allowed by GitHub, so I changed it to .txt
