### ISSUE TITLE
Background in "motion"-view

### ISSUE THREAD

**Issue by ChristianSaile** [bee-eater/SystemDumpViewer#12]
Hi,

I am not working with the latest version, so I am not sure if this is fixed already.
But in V2.3.0.27014 of the SystemDump Viewer the name of the axes are not readable

![Screenshot_SysDump_AxesNameMotion_SysDumpV2_3_0_27014](https://user-images.githubusercontent.com/95356645/144240757-46e34964-07de-4b9b-aa3c-11b9a92af8d2.png)

Maybe there could be an improvement of the readability.

Greetings
Christian

**Comment by bee-eater** [comment]
Hello Christian,

I'll have a look at it, thanks.

Best regards,
Marcel
