### ISSUE TITLE
FeatureRequest: Make data fields able to be copied

### ISSUE THREAD

**Issue by ChUnterberger** [bee-eater/SystemDumpViewer#16]
**Problem**
At the moment it is not possible to copy any of the field values (e.g. serial number) from the UI to the clipboard.
This would be helpful in a number of situations where currently you have to manually copy the content.

**Reproduction**
1. Load any system dump
2. Select Hardware
3. Select PLC
4. Try to copy value of B&R serial number
**ERROR: serial number cannot be selected and copied with CTRL + C to clipboard**
**EXPECTED: value part is selectable and can be copied with CRTL + C to clipboard**

**Version**
V2.4.4.28200

**Comment by bee-eater** [comment]
Hey @ChUnterberger,

sorry, somehow I wasn't notified about the new issues you created! I'll have a look at them as soon as possible!

Best regards,
Marcel
