### ISSUE TITLE
Websearch/Serialsearch prefix

### ISSUE THREAD

**Issue by SergiuNic** [bee-eater/SystemDumpViewer#20]
Hello,
In the latest available version 2.4.6.29018 I've noticed that te Websearch and Serialsearch are by default wrong. 
It would be nice to modify the address for both fields in:

https://www.br-automation.com/en/search/?q=

Thanks.

**Comment by bee-eater** [comment]
Hello Sergiu,

thanks for reporting! Could you specify "wrong"? 

The default settings should be something like:
![image](https://user-images.githubusercontent.com/34870259/213800788-b9549c5d-fc22-4cb5-a869-285cb5ca13f6.png)

which works fine for me.

Do you experience any issues with these default settings? Or is the de-de bothering you? 

Best regards,
Marcel

**Comment by bee-eater** [comment]
faeb0eb8a904925fc3357454411c43e12ebe6753
