### ISSUE TITLE
Search hardware in B&R Help

### ISSUE THREAD

**Issue by SergiuNic** [bee-eater/SystemDumpViewer#21]
Hello,

I've tried to update the path to Br.Help.Explorer.exe to the latest AS help V4.12 (EN) without success.
In my case: C:\BrAutomation\AS412\bin-en\BR.Help.Explorer.exe 
When I try to search for a hardware module in the latest BR Help i receive the following errors:

![2023-01-20_19-10-00](https://user-images.githubusercontent.com/87123778/213775156-526c6cbe-01ef-4ea5-8bd6-8347fd34b996.png)

It should be enough to add as launch parameter "/L:en" maybe when language english is selected.

Thanks

**Comment by bee-eater** [comment]
Hello Sergiu,

thanks for reporting!

I checked the command line argument thing you mentioned and `/L=[de,en]` does indeed work, thanks!!! Still, on my notebook, regardless the .exe I open (de / en) I always end up opening the German help. How does the help system decide which language it opens per default?? Why does yours try to open 'de' even though it's not installed and you selected the english .exe? I'm confused...

I'll add a dropdown to be able to select the desired language, which lists all installed languages based on the existance of the Help-xx\Data\brhelpcontent.xml file. That way you have all the oportunities, even if you have both languages installed! Does that sound like a valid solution to you? 

Best regards,
Marcel

**Comment by bee-eater** [comment]
Closing issue due to provided solution and missing feedback. Option presented above is planned for the next release (v2.5.0).
