### ISSUE TITLE
No IO information for safety modules

### ISSUE THREAD

**Issue by ChristianSaile** [bee-eater/SystemDumpViewer#24]
In the hardware tree, there are no IO information for some safety modules.
It works for: X20SL8100, X20SO6300
It does not work for: X20SI9100, X20SI4100, X20SO4120

These were the ones I had in my SystemDump

![Screenshot_SysDumpViewer_IoInformationSafetyModules](https://user-images.githubusercontent.com/95356645/217232079-ac8743fa-c93b-4135-8f5a-2b5c6211f8a2.png)

**Comment by bee-eater** [comment]
Hello Christian,

is that the same Systemdump as in the other issue?

Best regards,
Marcel

**Comment by ChristianSaile** [comment]
Hi Marcel,

yes it is the same one.

Thanks for your fast reply.

Greetings
Christian


Von: Marcel K. ***@***.***>
Gesendet: Dienstag, 7. Februar 2023 18:59
An: bee-eater/SystemDumpViewer ***@***.***>
Cc: Christian Saile ***@***.***>; Author ***@***.***>
Betreff: Re: [bee-eater/SystemDumpViewer] No IO information for safety modules (Issue #24)

BeSecure!
This email comes from outside of ABB. Make sure you verify the sender before clicking any links or downloading/opening attachments.
If this email looks suspicious, report it by clicking 'Report Phishing' button in Outlook or raising a ticket on MyIS.


Hello Christian,

is that the same Systemdump as in the other issue?

Best regards,
Marcel

-

**Comment by bee-eater** [comment]
Hello Christian,

so I checked the Systemdump.xml you provided and there is already no information about the channels in there!

![image](https://user-images.githubusercontent.com/34870259/217473300-3c604a24-d131-42e3-9a5e-332e23ef3edd.png)

You could ask B&R support why there is no info for these modules. 

Best regards,
Marcel

**Comment by ChristianSaile** [comment]
Hi,

alright I am asking the Int. Support about this too.

Thanks for the quick reply.


Greetings
Christian


Von: Marcel K. ***@***.***>
Gesendet: Mittwoch, 8. Februar 2023 09:19
An: bee-eater/SystemDumpViewer ***@***.***>
Cc: Christian Saile ***@***.***>; Author ***@***.***>
Betreff: Re: [bee-eater/SystemDumpViewer] No IO information for safety modules (Issue #24)

BeSecure!
This email comes from outside of ABB. Make sure you verify the sender before clicking any links or downloading/opening attachments.
If this email looks suspicious, report it by clicking 'Report Phishing' button in Outlook or raising a ticket on MyIS.


Hello Christian,

so I checked the Systemdump.xml you provided and there is already no information about the channels in there!

[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F34870259%2F217473300-3c604a24-d131-42e3-9a5e-332e23ef3edd.png&data=05%7C01%7Cchristian.saile%40br-automation.com%7C775a1e953ec2499f7e0e08db09ad2436%7C372ee9e09ce04033a64ac07073a91ecd%7C0%7C0%7C638114411464582092%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CYsoPsVus7vxRkDJNXDVEnCPn%2BZo5O3zON1Apg7glA4%3D&reserved=0>

You could ask B&R support why there is no info for these modules.

Best regards,
Marcel

-
