### ISSUE TITLE
ModuleOk = 2??

### ISSUE THREAD

**Issue by ChristianSaile** [bee-eater/SystemDumpViewer#25]
How can a "ModuleOk" BOOL have the value 2?

Shouldn´t this be a value 0-1?

![Screenshot_SysDumpViewer_ModulOk](https://user-images.githubusercontent.com/95356645/217232830-180dc6f9-2670-4494-8867-00b3ad5ced1e.png)
![Screenshot_AsHelp_ChannelList](https://user-images.githubusercontent.com/95356645/217233165-b847126d-f68e-4368-b7d0-550677b7babf.png)

**Comment by ChristianSaile** [comment]
Sorry, forgot my SystemDump.

Maybe this will help to get also the problems

[BuR_SDM_Sysdump_2022_12_02_10_48_21-687f04.tar.gz](https://github.com/bee-eater/SystemDumpViewer/files/10674539/BuR_SDM_Sysdump_2022_12_02_10_48_21-687f04.tar.gz)

**Comment by bee-eater** [comment]
Hello Christian,

if you check the xml file you'll see that the "2" is already exported by the systemdump of the SDM. I'll check if I find the description somewhere, otherwise you could open up a ticket with B&R support.

Best regards,
Marcel

**Comment by ChristianSaile** [comment]
Hi Marcel,

thank you for the hint.
I opened up a ticket, and asked Eggelsberg for support.


Greetings
Christian


Von: Marcel K. ***@***.***>
Gesendet: Dienstag, 7. Februar 2023 18:58
An: bee-eater/SystemDumpViewer ***@***.***>
Cc: Christian Saile ***@***.***>; Author ***@***.***>
Betreff: Re: [bee-eater/SystemDumpViewer] ModuleOk = 2?? (Issue #25)

BeSecure!
This email comes from outside of ABB. Make sure you verify the sender before clicking any links or downloading/opening attachments.
If this email looks suspicious, report it by clicking 'Report Phishing' button in Outlook or raising a ticket on MyIS.


Hello Christian,

if you check the xml file you'll see that the "2" is already exported by the systemdump of the SDM. I'll check if I find the description somewhere, otherwise you could open up a ticket with B&R support.

Best regards,
Marcel

-
