### ISSUE TITLE
Windows 11 support

### ISSUE THREAD

**Issue by janbirki** [bee-eater/SystemDumpViewer#34]
Hi 

First of all thanks for your great work! :)

Are you aware that the installation of the systemDumpViewer is not working on Windows 11? I tried it with the latest release and the installation process didn't start at all. 

Thanks for your reply!

**Comment by janbirki** [comment]
Hey  @bee-eater 

Thanks for your fast reply. 

Indeed I tried it as admin but the effect was the same. The loading circle appeared for several seconds and nothing more happened. So there was no error message or other message. I installed it afterwards on a Win10 machine from a colleague and it was working perfect. So I assume that anti virus shouldn't be an issue.

**Comment by bee-eater** [comment]
Hey @janbirki 

Could you please try the attached setup? It's a shot in the dark but I recompiled it with a new InnoSetup version since that seems to be the issue with the installer not even opening... To still use the SystemdumpViewer you should be able to just copy the program files of an existing installation to your computer!

[Setup_SystemdumpViewer_2_5_1_29109.zip](https://github.com/bee-eater/SystemDumpViewer/files/11419242/Setup_SystemdumpViewer_2_5_1_29109.zip)

**Comment by bee-eater** [comment]
So I setup a Win 11 Pro in a VM and I could install both versions fine. Probably something blocks the admin request? Could you check your windows event logs? Not sure why it crashes on your system...

**Comment by janbirki** [comment]
Hi
 Thanks for your effort. I tried to install it with your submitted installation file and it worked. So I could install it. Is that comprehensible for you? :)
Thanks!
Cheers
Jan
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 08/05/2023 - 13:39 (CEST)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [bee-eater/SystemDumpViewer] Windows 11 support (Issue #34)
So I setup a Win 11 Pro in a VM and I could install both versions fine. Probably something blocks the admin request? Could you check your windows event logs? Not sure why it crashes on your system...

**Comment by bee-eater** [comment]
Hey @janbirki,

so then it indeed seems like the updated installer version somehow did the trick. For me in the VM it also worked with the old setup, but still, since it works for you I'll update the setup in the repository!

Thanks for your support!

Best regards,
Marcel

**Comment by bee-eater** [comment]
Updated latest release with new installer

**Comment by janbirki** [comment]
Greaf, thanks a lot! On May 10, 2023 07:46, "Marcel K." ***@***.***> wrote:
Hey @janbirki,
so then it indeed seems like the updated installer version somehow did the trick. For me in the VM it also worked with the old setup, but still, since it works for you I'll update the setup in the repository!
Thanks for your support!
Best regards,
Marcel
