### ISSUE TITLE
Does not always show all the system dump entries

### ISSUE THREAD

**Issue by trinityspeed** [bee-eater/SystemDumpViewer#7]
Systemdump Viewer 2.3.0.27014
Systemdump created with APC2100 BY44 / AR B4.38

When loading a system dump into the systemdump viewer there are a significant number of log messages missing compared to when opening the dump in the automation studio. I couldn't find any pattern. It's not related to a specific logger, time or severity.

Any thoughts?

[BuR_SDM_Sysdump_2021-04-20_08-58-14.tar.gz](https://github.com/bee-eater/SystemDumpViewer/files/6344817/BuR_SDM_Sysdump_2021-04-20_08-58-14.tar.gz)

**Comment by bee-eater** [comment]
Hey trinityspeed!

That is because the actual xml file of the Systemdump only contains, I think it was 100 lines per logger! 

Only the Systemdump.xml is displayed in the application, not the additional data files. Those have to be opened with automation studio.

Best regards,
Marcel

**Comment by trinityspeed** [comment]
Hi Marcel
Wow awesome response time ;-).
Has this changed in the last couple of months.
Will this be considered in a next version of the system dump viewer?

Thanks for helping out.
Have a great day
Patrick

**Comment by bee-eater** [comment]
Hey Patrick,

no, as far as I remember that’s the was it has always been. 

Currently there is no active development on the SDV. But I will check the effort and see if I can spare some time. No promises :-)

Best regards,
Marcel

**Comment by trinityspeed** [comment]
Hey Marcel

Thanks for your support.
Don't we all wish for some spare time ;-).

Best regards,
Patrick
