### ISSUE TITLE
Window opening in between two screens

### ISSUE THREAD

**Issue by SergiuNic** [bee-eater/SystemDumpViewer#9]
Hello,

since the very first versions, when opening the app, the window end up in "strange" position - see attachment.

Is there any way to solve this inconvenient? 

Thanks
![position](https://user-images.githubusercontent.com/87123778/124901821-a5ab4500-dfe2-11eb-8cd9-406c2c04936f.jpg)

**Comment by bee-eater** [comment]
Hello @SergiuNic,

the default behavior should be, that the program opens in the middle of your screen! If you have two or more screens it can be that it starts in a position like in your screenshot. 

To change it, you can move the window to a desired position and save the position via the menu:
![image](https://user-images.githubusercontent.com/34870259/124910758-389cad00-dfec-11eb-9422-0f8ae0680fae.png)

Best regards,
Marcel

**Comment by SergiuNic** [comment]
Hello @bee-eater ,

thank you for the fast reply.
I was not aware about this option.
Thanks.
